In [35]:
import numpy as np

#create array from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d, arr2d.shape)

#Create
arr1 = np.zeros((2,3) , dtype="int64") # prefill
print(arr1, arr1.shape)

arr2 = np.ones((2,3) , dtype="int64") # prefill
print(arr2, arr2.shape)

arr3 = np.full((2,3),100 , dtype="int64") # prefill with value
print(arr3, arr3.shape)

arr4 = np.eye(2 , dtype="int64") #Identity
print(arr4, arr4.shape)

arr5 = np.arange(0, 11, 2) # Identity
print(arr5, arr5.shape)

arr6 = np.linspace(1,100,4) # prefill
print(arr6, arr6.shape)


[1 2 3 4 5] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1 0]
 [0 1]] (2, 2)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [40]:
#Change the dimensions
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened = arr.flatten() #2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [41]:
#Indexing
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[3])



1
4
